# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 82, 731, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.textEdit_filename = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.textEdit_filename.setObjectName("textEdit_filename")
        self.horizontalLayout.addWidget(self.textEdit_filename)
        self.pushButton_load = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_load.setObjectName("pushButton_load")
        self.horizontalLayout.addWidget(self.pushButton_load)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 460, 751, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_StartCapture = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_StartCapture.setObjectName("pushButton_StartCapture")
        self.horizontalLayout_2.addWidget(self.pushButton_StartCapture)
        self.pushButton_StopCapture = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_StopCapture.setObjectName("pushButton_StopCapture")
        self.horizontalLayout_2.addWidget(self.pushButton_StopCapture)
        self.pushButton_FacialPoint = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_FacialPoint.setCheckable(True)
        self.pushButton_FacialPoint.setObjectName("pushButton_FacialPoint")
        self.horizontalLayout_2.addWidget(self.pushButton_FacialPoint)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(150, 20, 481, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(180, 130, 441, 291))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.canvas = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.canvas.setAlignment(QtCore.Qt.AlignCenter)
        self.canvas.setObjectName("canvas")
        self.horizontalLayout_3.addWidget(self.canvas)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menu_About = QtWidgets.QMenu(self.menubar)
        self.menu_About.setObjectName("menu_About")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_Exit = QtWidgets.QAction(MainWindow)
        self.action_Exit.setObjectName("action_Exit")
        self.action_About = QtWidgets.QAction(MainWindow)
        self.action_About.setObjectName("action_About")
        self.menu_File.addAction(self.action_Exit)
        self.menu_About.addAction(self.action_About)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_About.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Model filename:"))
        self.pushButton_load.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_StartCapture.setText(_translate("MainWindow", "Start Capture"))
        self.pushButton_StopCapture.setText(_translate("MainWindow", "Stop Capture"))
        self.pushButton_FacialPoint.setText(_translate("MainWindow", "Predict Facial Point"))
        self.label_2.setText(_translate("MainWindow", "W207 - Project4: Facial KeyPoint Detection"))
        self.canvas.setText(_translate("MainWindow", "Image not shown yet"))
        self.menu_File.setTitle(_translate("MainWindow", "&File"))
        self.menu_About.setTitle(_translate("MainWindow", "&About"))
        self.action_Exit.setText(_translate("MainWindow", "&Exit"))
        self.action_About.setText(_translate("MainWindow", "&About"))
